[repository]
name = "hyprmodoro"
authors = ["0xFMD", "luccaugusto"]
commit_pins = []

[hyprmodoro]
description = "A Pomodoro timer plugin for Hyprland"
authors = ["0xFMD", "luccaugusto"]
output = "hyprmodoro.so"
build = ["make all"]
