[repository]
name = "hyprmodoro"
authors = ["0xFMD", "luccaugusto"]
commit_pins = [
  ["f7aae0b2a7811815ffbab7ab10a4ddaae71e36e1", "348c1624fac6c93f57a06902e7ef2c0775515a73"], # Hyprland v0.50.1
  ["2174fa6a88d807aa00b5fdd6ced9633be6fe783c", "46174f78b374b6cea669c48880877a8bdcf7802f"], # Hyprland v0.51.0
  ["71a1216abcc7031776630a6d88f105605c4dc1c9", "264483d9c06f59c9cc684e7fbfc7e46a6220a5d2"], # Hyprland v0.51.1
  ["f56ec180d3a03a5aa978391249ff8f40f949fb73", "c7efdcb1b52caaf889c64256d537f27e0b5520b6"], # Hyprland v0.52.0
  ["967c3c7404d4fa00234e29c70df3e263386d2597", "c7efdcb1b52caaf889c64256d537f27e0b5520b6"], # Hyprland v0.52.1
  ["ea444c35bb23b6e34505ab6753e069de7801cc25", "c7efdcb1b52caaf889c64256d537f27e0b5520b6"], # Hyprland v0.53.0
  ["ab1d80f3d6aebd57a0971b53a1993b1c1dfe0b09", "c7efdcb1b52caaf889c64256d537f27e0b5520b6"]  # Hyprland v0.53.1
]

[hyprmodoro]
description = "A Pomodoro timer plugin for Hyprland"
authors = ["0xFMD", "luccaugusto"]
output = "hyprmodoro.so"
build = ["make all"]
